Docs v3 | VitePress Rewrite
Faithful-Resource-Pack/Docs pull request #36
Opened 2024-04-10 06:27 UTC by 3vorp

The current docs site is rapidly falling apart since it's never actually been maintained properly, so I replaced it with a low-maintenance docs generator with very little configuration.

All the routes are the same as the old site, and the site is entirely static now so it can be served directly over apache like the web app. Pretty much all the existing docs were ported without changes except for tables of contents and some formatting classes.

It's also only three dependencies and extremely lightweight, since I didn't have to build everything from the ground up. (why did we do this in the first place with docs v2 lol)

Here's some images of the new site (it's just the default VitePress theme).

<img width="1680" alt="Screen Shot 2024-04-09 at 11 20 18 PM" src="https://github.com/Faithful-Resource-Pack/Docs/assets/75297863/f98e1ac8-9cd1-4797-8461-e473f57f33fa">

<img width="1680" alt="Screen Shot 2024-04-09 at 11 21 00 PM" src="https://github.com/Faithful-Resource-Pack/Docs/assets/75297863/96326996-f258-4c34-99a3-6cbfbf5f6370">

<img width="1680" alt="Screen Shot 2024-04-09 at 11 21 18 PM" src="https://github.com/Faithful-Resource-Pack/Docs/assets/75297863/a36c9df1-8788-47c3-812a-3f22baf96067">

This PR closes #31

2024-04-10 12:01 UTC, TheRolfFR requested changes
overall good, but we should increase nav bar size and use the whole page on the side with larger content width

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +	postDate.setFullYear(year);
I would have computed the time as a number and then just make a date object from the sum

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +	if (isNaN(postDate.getTime())) return false;
and no error checking, just let him live its life

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +	return postDate.getTime() > delayedDate.getTime();
and then just compare delate date time.

If fyou want to optimize this, don't compute the delayed date time each function run, just one and then compare or be smart and if second argument delayed_date_time is undefined, compute it

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +}>();
it can be a list and an item? confusing

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +	props.item.link && toggle();
don't try to be as low code as possible, minifier will do the job for you, increase readability instead
```suggestion
	// if sublist and (click or "Enter" key)
	if (!props.item.link && (!("key" in e) || e.key === "Enter"))
		toggle();
}

function onCaretClick() {
	if(props.item.link)
		toggle();
```

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +				tabindex="0"
aren't we supposed to put a real value here?

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +				v-html="item.text"
no html

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +}
add padding transition to smooth things out

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +	left: -17px;
no, those adjustments need a real solution, no workarounds, find rootcause and fix

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +.SidebarItemOverride.level-5.has-active > .item > .link > .text {
for this one and the siblings, you should consider using a better class name or add another one just to reduce clutter, no with no mention to level, is it even necessary with ``.SidebarItemOverride`` ? (btw class name should be kebab-case)

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +	margin-right: -7px;
yeah no this -7px is fucked up, find the root cause

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +.SidebarItemOverride.level-5 .items {
no level or new class needed

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +	display: none;
maybe use max-width, overflow hidden and transition to slide up content?

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/components/SidebarItemOverride.vue
> +	transition: transform 0.25s;
0.25s should be a variable to get same value for all collapse transitions

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/config.ts
> +	if (dir.at(-1) != "/") dir += "/";
use [path.sep](https://nodejs.org/api/path.html#pathsep) instead

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/config.ts
> +			filelist = walkSync(dir + file + "/", filelist);
path.sep

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/config.ts
> +			filelist = walkSync(dir + file + "/", filelist);
Use async methods and maps to increase performance

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/config.ts
> +		const file = readFileSync(fileName, { encoding: "utf8" });
stop reading sync

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/config.ts
> +		socialLinks: [{ icon: "github", link: "https://github.com/faithful-resource-pack" }],
X link? curseforge? website at least?

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/config.ts
> +		socialLinks: [{ icon: "github", link: "https://github.com/faithful-resource-pack" }],
Store / get some values from API like indicated in the dynamic config resolution (https://vitepress.dev/reference/site-config#config-resolution) ?

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/config.ts
> +			copyright: "© 2024 Faithful Resource Pack",
dynamic year gen?

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/config.ts
> +				"NOT AN OFFICIAL MINECRAFT PRODUCT. NOT APPROVED BY OR ASSOCIATED WITH MOJANG OR MICROSOFT",
store disclaimer into API?

2024-04-10 12:01 UTC, TheRolfFR commented on .vitepress/theme/styles.css
> +}
check contrast for uses

2024-04-10 15:30 UTC, 3vorp commented on .vitepress/components/SidebarItemOverride.vue
> +	return postDate.getTime() > delayedDate.getTime();
good idea, I just took this from the svelte site

2024-04-10 15:36 UTC, 3vorp commented on .vitepress/components/SidebarItemOverride.vue
> +}>();
this is entirely taken from existing vitepress code, I needed to override it to add badges and this was the only working solution

2024-04-10 15:45 UTC, 3vorp commented on .vitepress/components/SidebarItemOverride.vue
> +	postDate.setFullYear(year);
or honestly we could just use YMD strings which dates can parse easily, idk whichever is easier

2024-04-10 23:51 UTC, 3vorp commented on .vitepress/config.ts
> +			filelist = walkSync(dir + file + "/", filelist);
this is only used once on build anyways, and currently the entire app builds in less than 5 seconds (which this function is less than 0.5 seconds of)

2024-04-13 11:27 UTC, TheRolfFR approved these changes

2024-04-13 11:27 UTC, TheRolfFR commented on .vitepress/config.ts
> +					This website was made using the <a href="https://vitepress.dev">VitePress</a> framework. View the source <a href="https://github.com/Faithful-Resource-Pack/Docs">here</a>!
target="_blank"

2024-04-13 18:26 UTC, merged